name: Lint Files

# This workflow lints the docsapp directory
# And will trigger on push to *any* branch except main
on:
  push:
    branches-ignore:
      - master

jobs:
  lint-client:
    name: Lint Client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6

      - name: Use NodeJS v24
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install Dependencies and Lint
        run: |
          cd docsapp
          npm ci
          npm run lint
